### ISSUE TITLE
field IntermediateSchema.finc.mega_collection should be type array

### ISSUE THREAD

**Issue by gertho** [miku/span#3]
in consequence of https://github.com/ubleipzig/intermediateschema/issues/4 the field IntermediateSchema.finc.mega_collection should be an array too

**Comment by miku** [comment]
Thanks a lot. This is addressed in a05d018c9174fd939cbbd9dacb36f80273ea04dd and released with [v0.1.184](https://github.com/miku/span/releases/tag/v0.1.184).

**Comment by miku** [comment]
This change required a couple of adjustments in preprocessing, e.g. https://github.com/miku/siskin/commit/60cfd4ab9ba69b2061efc0fd1316a99d1b1bc8da, https://github.com/miku/siskin/commit/a54a24f9c51c98ffd75c1f4f6e1f318710778bb5, https://github.com/miku/siskin/commit/051bca3dafc89027e3e7dde35efa1ebbb37f3653, https://github.com/miku/siskin/commit/9f29b2580b40c6524534ee08b3318b8625af0e3c - but that should be all. The current index update has been already built with this change, so I would close this issue.
