### ISSUE TITLE
map is:rft.pages to (e.g.) finc:physical 

### ISSUE THREAD

**Issue by zazi** [miku/span#5]
currently there is no mapping (in the [intermediate schema to finc Solr schema mapping script)](https://github.com/miku/span/blob/master/formats/finc/solr.go) from intermediate schema field "rft.pages" to a field of the finc Solr schema (e.g. finc:physical). can we add a mapping for this field, please?

**Comment by miku** [comment]
Should be ok with https://github.com/miku/span/commit/5518513d5d5d8c2b24ba18f2f38805d91b86d465, included in new [v0.1.193](https://github.com/miku/span/releases/tag/v0.1.193) release.
