### ISSUE TITLE
map is:abstract to (e.g.) finc:description

### ISSUE THREAD

**Issue by zazi** [miku/span#6]
currently there is no mapping (in the [intermediate schema to finc Solr schema mapping script](https://github.com/miku/span/blob/master/formats/finc/solr.go)) from intermediate schema field "abstract" to a field of the finc Solr schema (e.g. finc:description). can we add a mapping for this field, please?

**Comment by zazi** [comment]
thx @miku for this fast fix ;)

**Comment by miku** [comment]
@zazi, np, should be included in [v0.1.198](https://github.com/miku/span/releases/tag/v0.1.198).
