### ISSUE TITLE
add a mapping from a property that holds the original record identifier in intermediate schema to field "record_id" in finc Solr schema (via span-export)

### ISSUE THREAD

**Issue by zazi** [miku/span#7]
[issue#7 of intermediateschema](https://github.com/ubleipzig/intermediateschema/issues/7) is related to this topic. Currently, we only have a mapping from field "finc.record_id" in intermediate schema to field "id" in finc Solr schema (see https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/solr.go#L86), which requires that the record identifier needs to follow a certain pattern (which is [PREFIX]-[SOURCE-ID]-[BASE64-ENCODED-ORIGINAL-RECORD-ID]). However, we need a mapping from a field in the intermediate schema records that holds the original record identifier to the field "record_id" in finc Solr schema (via span-export).

**Comment by zazi** [comment]
could be closed with https://github.com/miku/span/releases/tag/v0.1.205 (?)

**Comment by miku** [comment]
Yes, just a bit more testing in the wild.

**Comment by miku** [comment]
Seems to work, closing this for now.
