### ISSUE TITLE
add a mapping from an author's property (e.g. rft.au) in intermediate schema to field "author_sort" in finc Solr schema (via span-export)

### ISSUE THREAD

**Issue by zazi** [miku/span#8]
currently, there is no mapping to this field via span-export. however, the field "author_sort" in finc Solr schema needs to be filled to allow author sorting. a proposal: take the first author (rft.au) and convert the name to lowercase.

**Comment by zazi** [comment]
After a proper re-evaluation of the field "author_sort", we recognized that this field is not marked as multivalued, i.e., only one value is allowed for "author_sort".

**Comment by miku** [comment]
Thanks - [0.1.212](https://github.com/miku/span/releases/tag/v0.1.212) hopefully addresses this.
